### PR TITLE
Fixed conflicting properties warning

### PR DESCRIPTION
**Pull request by sredni**
When shorthand css property is used along with specific one react dev tools throws warning:

```
Warning: Updating a style property during rerender (animation) when a conflicting property is set (animationDelay) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values.
```

This PR contains small macos metadata files cleanup ;)

### CODE REVIEW

**Comment by sredni** [comment]
Actually fixes #2

**Comment by sredni** [comment]
Would be also nice if you will rollout new version to npm

**Comment by mijim** [comment]
New version added with your fix. @sredni would you like to join as a collaborator to the package?

**Comment by sredni** [comment]
@mijim sure, if I will have some spare time I can take a look at Issues/PRs. Also since I'm currently using it in my app I will probably test it well ;)

**Comment by mijim** [comment]
Thanks @sredni, added 😉 🤜🏼

**Pull request merged**
