### PR TITLE
Update typings

### PR DESCRIPTION
**Pull request by nathnhughes**
When using RMA in a recent project, I found that the types weren't particularly robust and so took a look at refining them in order to make the `Animated` component a little safer.

Take a look and feel free to merge or expand on my initial revisions 👍

### CODE REVIEW

**Comment by nathnhughes** [comment]
Also added support for `mountTimingFunction` and `unmountTimingFunction` props with 7197432

**Comment by mijim** [comment]
@nathnhughes your pull is so great, thanks! Would you like me to put you as a collaborator?

**Comment by nathnhughes** [comment]
@mijim thanks, that would be great!

**Comment by mijim** [comment]
@nathnhughes I need your npm user name to add you as a maintainer. If you don't have it's as easy as login with your github account

**Pull request merged**
